<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>ProfileShift</AssemblyName>
    <RootNamespace>ProfileShift</RootNamespace>
    <ApplicationIcon>ProfileShiftIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="ProfileShiftIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="15.1.4" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
